# Generated by Django 4.0.2 on 2022-02-23 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('product_list', models.CharField(default='', max_length=500)),
                ('quantity', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=122)),
                ('email', models.EmailField(default='', max_length=122)),
                ('phone', models.CharField(default='', max_length=15)),
                ('address', models.CharField(default='', max_length=122)),
                ('city', models.CharField(default='', max_length=50)),
                ('pincode', models.CharField(default='', max_length=15)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('payment_id', models.CharField(default='', max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
