# Generated by Django 4.0.2 on 2022-02-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
